"""initial_schema

Revision ID: 0a8e01f7b363
Revises: 
Create Date: 2026-04-17 13:02:54.258198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a8e01f7b363'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure the pgvector extension is available before creating tables that use it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_document_chunks_candidate_id'), 'document_chunks', ['candidate_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_document_chunks_workflow_run_id'), 'document_chunks', ['workflow_run_id'], unique=False, if_not_exists=True)
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('vacancy_id', sa.String(length=64), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=256), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporal_workflow_id'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_workflow_runs_candidate_id'), 'workflow_runs', ['candidate_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_workflow_runs_vacancy_id'), 'workflow_runs', ['vacancy_id'], unique=False, if_not_exists=True)
    op.create_table('analysis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('vacancy_id', sa.String(length=64), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('skill_match_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('risk_penalty', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=32), nullable=False),
    sa.Column('report_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.create_index(op.f('ix_analysis_reports_candidate_id'), 'analysis_reports', ['candidate_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_analysis_reports_vacancy_id'), 'analysis_reports', ['vacancy_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_reports_vacancy_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_candidate_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_workflow_runs_vacancy_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_candidate_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_document_chunks_workflow_run_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_candidate_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
